name: "PROD DEPLOY"

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml
    with:
      environment: pro
    secrets:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID }}
      DATABRICKS_CLIENT_SECRET: ${{ secrets.DATABRICKS_CLIENT_SECRET }}

  sync-dags:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read destroy configuration
        id: read-destroy-config
        run: |
          DESTROY="$(jq -r '.pro' ./IaC/destroy_config.json)"
          echo "destroy=$(echo $DESTROY)" >> $GITHUB_OUTPUT   

      - name: Configure AWS credentials
        if: steps.read-destroy-config.outputs.destroy != 'true'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::120945137272:role/github-actions-data-master
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: us-east-2

      - name: Upload DAGs to S3
        if: steps.read-destroy-config.outputs.destroy != 'true'
        run: |
          aws s3 cp app/src/airflow/dags/ s3://pro-us-east-2-data-master/dags/ --recursive --exclude "*" --include "*.py"
