name: 'Databricks Terraform CI/CD'

on:
  push:
    branches:
      - develop

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: dev
    env:
      DATABRICKS_AUTH_TYPE: github-oidc
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          # Optional: specify terraform version
          terraform_version: 1.8.2

      - name: Install Databricks CLI
        uses: databricks/setup-cli@main

      - name: Terraform Init
        run: cd IaC && terraform init
        # If using a remote backend, ensure credentials are provided via environment variables or configuration

      - name: Terraform Plan
        run: cd IaC && terraform plan

      - name: Terraform Apply        
        run: cd IaC && terraform apply -auto-approve
